#ifndef KEYWORDS_H
#define KEYWORDS_H

enum keyWords
{
    UNKNOWN = '?',            // for getopt
    ABOVE, ABSOLUTE, ALIGN, ANCIENT, ARC_COLOR, ARC_FILE, AUTO, AZIMUTHAL, 
    BACKGROUND, BELOW, BODY,
    CENTER, CIRCLE, CLOUD_GAMMA, CLOUD_MAP, CLOUD_THRESHOLD, COLOR, CONFIG_FILE, 
    DATE, DATE_FORMAT, DAY_MAP, DELIMITER, DRAW_ORBIT, 
    ENDOFLINE, EPHEMERIS, 
    FONT, FONTSIZE, FOV, 
    GALACTIC, GEOMETRY, GMTLABEL, GRID, GRID1, GRID2, GRID_COLOR, GROUND, 
    HEMISPHERE, HIBERNATE,
    IDLEWAIT, IMAGE, 
    JDATE,
    LABEL, LABELPOS, LATITUDE, LATLON, LBR, LEFT, LIGHT_TIME, LOCALTIME, LONGITUDE, 
    MAGNIFY, MAJOR, MAKECLOUDMAPS, MAPBOUNDS, MARKER_BOUNDS, MARKER_COLOR, MARKER_FILE, MARKER_FONT, MAX_RAD_FOR_LABEL, MIN_RAD_FOR_LABEL, MIN_RAD_FOR_MARKERS, MERCATOR, MOLLWEIDE, MULTIPLE,
    NAME, NIGHT_MAP, NORTH, NUM_TIMES, 
    OUTPUT, ORBIT, ORBIT_COLOR, ORIGIN, ORIGINFILE, ORTHOGRAPHIC, 
    PETERS, POSITION, POST_COMMAND, PREV_COMMAND, PROJECTION, 
    QUALITY, 
    RADIUS, RANDOM, RANDOM_ORIGIN, RANDOM_TARGET, RANGE, RECTANGULAR, RIGHT, ROOT, ROTATE, 
    SATELLITE_FILE, SEARCHDIR, SHADE, SPACING, SPECULAR_MAP, STARFREQ, STARMAP, SYMBOLSIZE, SYSTEM, 
    TARGET, TERRESTRIAL, TEXT_COLOR, TIMEWARP, TIMEZONE, TMPDIR, TRAIL, TRANSPARENT, TRANSPNG,
    VERBOSITY, VERSIONNUMBER, VROOT, 
    WAIT, WINDOW, WINDOWTITLE, 
    LAST_WORD
};

const char * const keyWordString[LAST_WORD] =
{
    "UNKNOWN",
    "ABOVE", "ABSOLUTE", "ALIGN", "ANCIENT", "ARC_COLOR", "ARC_FILE", "AUTO", "AZIMUTHAL", 
    "BACKGROUND", "BELOW", "BODY",
    "CENTER", "CIRCLE", "CLOUD_GAMMA", "CLOUD_MAP", "CLOUD_THRESHOLD", "COLOR", "CONFIG_FILE", 
    "DATE", "DATE_FORMAT", "DAY_MAP", "DELIMITER", "DRAW_ORBIT", 
    "ENDOFLINE", "EPHEMERIS", 
    "FONT", "FONTSIZE", "FOV", 
    "GALACTIC", "GEOMETRY", "GMTLABEL", "GRID", "GRID1", "GRID2", "GRID_COLOR", "GROUND", 
    "HEMISPHERE", "HIBERNATE",
    "IDLEWAIT", "IMAGE", 
    "JDATE",
    "LABEL", "LABELPOS", "LATITUDE", "LATLON", "LBR", "LEFT", "LIGHT_TIME", "LOCALTIME", "LONGITUDE", 
    "MAGNIFY", "MAJOR", "MAKECLOUDMAPS", "MAPBOUNDS", "MARKER_BOUNDS", "MARKER_COLOR", "MARKER_FILE", "MARKER_FONT", "MAX_RAD_FOR_LABEL", "MIN_RAD_FOR_LABEL", "MIN_RAD_FOR_MARKERS", "MERCATOR", "MOLLWEIDE", "MULTIPLE",
    "NAME", "NIGHT_MAP", "NORTH", "NUM_TIMES", 
    "OUTPUT", "ORBIT", "ORBIT_COLOR", "ORIGIN", "ORIGINFILE", "ORTHOGRAPHIC", 
    "PETERS", "POSITION", "POST_COMMAND", "PREV_COMMAND", "PROJECTION", 
    "QUALITY", 
    "RADIUS", "RANDOM", "RANDOM_ORIGIN", "RANDOM_TARGET", "RANGE", "RECTANGULAR", "RIGHT", "ROOT", "ROTATE", 
    "SATELLITE_FILE", "SEARCHDIR", "SHADE", "SPACING", "SPECULAR_MAP", "STARFREQ", "STARMAP", "SYMBOLSIZE", "SYSTEM", 
    "TARGET", "TERRESTRIAL", "TEXT_COLOR", "TIMEWARP", "TIMEZONE", "TMPDIR", "TRAIL", "TRANSPARENT", "TRANSPNG",
    "VERBOSITY", "VERSIONNUMBER", "VROOT", 
    "WAIT", "WINDOW", "WINDOWTITLE", 
    "LAST_WORD"
};

#endif
